### PR TITLE
Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-python-library.git`](https://github.com/cisagov/skeleton-python-library.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
:zap:

**Review by dav3r — APPROVED** [review]
👍

**Review by hillaryj — APPROVED** [review]
🌮

**Comment by hillaryj** [comment]
@felddy Test is failing on a snyk test in your account, looks like.

**Comment by jsf9k** [comment]
@felddy, please merge this PR or explain why it cannot be merged.  I don't even have permission to view the Snyk failure under your username.

I'll go ahead and merge COB on 9/18/2020 unless we hear from you.  Now hold out your hand so I can rap your knuckles with a ruler!

**Pull request merged**
